force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <displayFormat>STU-{0000}</displayFormat>
        <label>Student Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Username</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/StudentTriggerTest.cls
@IsTest
private class StudentTriggerTest {
    
    @IsTest
    static void testStudentNameConcatenation() {
        Test.startTest();
        // Insert student with first and last name
        Student__c s = new Student__c(
            First_Name__c = 'Yunus',
            Last_Name__c = 'Emre',
            Username__c = 'yunus@example.com'
        );
        insert s;
        
        // Assertions
        Student__c queriedStudent = [SELECT Name FROM Student__c WHERE Id = :s.Id];
        System.assertEquals('Yunus Emre', queriedStudent.Name, 'Student name should automatically concatenate.');
        
        // Update student first name
        s.First_Name__c = 'Mehmet';
        update s;
        
        queriedStudent = [SELECT Name FROM Student__c WHERE Id = :s.Id];
        System.assertEquals('Mehmet Emre', queriedStudent.Name, 'Student name should automatically update upon changes.');
        Test.stopTest();
    }
}